#!/bin/sh

#This requires that user runs 'dotcloud var set app LOGENTRIES_ACCOUNT_KEY=abcdef......' before adding this script to their app
key=$(cat /home/dotcloud/environment.json | /usr/bin/python -c 'import json,sys;obj=json.loads(sys.stdin.read());print obj["'"LOGENTRIES_ACCOUNT_KEY"'"]')
nodename=$(uname -n)

# Create the data folder, if existing it won't be overridden
if [ ! -d "/home/dotcloud/data" ]; then
    mkdir /home/dotcloud/data
fi

# Quietly download Logentries agent, this will be downloaded every deploy
wget -q -O /home/dotcloud/le https://github.com/logentries/le_dotcloud/raw/master/le
chmod +x /home/dotcloud/le

# Check if the config exists, indicating server has already been registered
# TODO - This isn't working, it appears ~/data is moved before postinstall is run
if [ ! -f "/home/dotcloud/data/.le/config" ]; then

	/home/dotcloud/le register --user-key=$key

	/home/dotcloud/le follow "/var/log/nginx/$nodename.access.log"
	/home/dotcloud/le follow "/var/log/nginx/$nodename.error.log"	
fi

exit 0
